# Generated by Django 4.1.4 on 2023-01-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0003_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='defective_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect_date', models.DateField()),
                ('item', models.CharField(max_length=100)),
                ('issue', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
    ]
