# Generated by Django 4.1.4 on 2023-01-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0004_defective_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='all_supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateField()),
                ('Name', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Email', models.CharField(max_length=100)),
                ('Supp_Item', models.CharField(max_length=100)),
                ('purchase', models.IntegerField()),
            ],
        ),
    ]
